using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Metadata.Builders;
using NexusBilling.Core.Domain.Common;
using NexusBilling.Core.Domain.Administration.Entities;

namespace NexusBilling.Infrastructure.Persistence.Administration.Configurations;

public class ServiceHeaderConfiguration : IEntityTypeConfiguration<ServiceHeader>
{
    public void Configure(EntityTypeBuilder<ServiceHeader> builder)
    {
        builder.ToTable("service_header", "administration");
        builder.HasKey(x => x.Id);
        builder.Property(x => x.TenantId).HasConversion(v => v.Value, v => TenantIdentifier.Create(v)).HasColumnName("tenant_id").IsRequired();
        builder.Property(x => x.DocumentType).HasColumnName("document_type");
        builder.Property(x => x.CustomerNo).HasColumnName("customer_no");
        builder.Property(x => x.No).HasColumnName("no");
        builder.Property(x => x.BillToCustomerNo).HasColumnName("bill_to_customer_no");
        builder.Property(x => x.BillToName).HasColumnName("bill_to_name");
        builder.Property(x => x.BillToName2).HasColumnName("bill_to_name_2");
        builder.Property(x => x.BillToAddress).HasColumnName("bill_to_address");
        builder.Property(x => x.BillToAddress2).HasColumnName("bill_to_address_2");
        builder.Property(x => x.BillToCity).HasColumnName("bill_to_city");
        builder.Property(x => x.BillToContact).HasColumnName("bill_to_contact");
        builder.Property(x => x.YourReference).HasColumnName("your_reference");
        builder.Property(x => x.ShipToCode).HasColumnName("ship_to_code");
        builder.Property(x => x.ShipToName).HasColumnName("ship_to_name");
        builder.Property(x => x.ShipToName2).HasColumnName("ship_to_name_2");
        builder.Property(x => x.ShipToAddress).HasColumnName("ship_to_address");
        builder.Property(x => x.ShipToAddress2).HasColumnName("ship_to_address_2");
        builder.Property(x => x.ShipToCity).HasColumnName("ship_to_city");
        builder.Property(x => x.ShipToContact).HasColumnName("ship_to_contact");
        builder.Property(x => x.OrderDate).HasColumnName("order_date");
        builder.Property(x => x.PostingDate).HasColumnName("posting_date");
        builder.Property(x => x.PostingDescription).HasColumnName("posting_description");
        builder.Property(x => x.PaymentTermsCode).HasColumnName("payment_terms_code");
        builder.Property(x => x.DueDate).HasColumnName("due_date");
        builder.Property(x => x.PaymentDiscount).HasColumnName("payment_discount").HasPrecision(18, 5);
        builder.Property(x => x.PmtDiscountDate).HasColumnName("pmt_discount_date");
        builder.Property(x => x.ShipmentMethodCode).HasColumnName("shipment_method_code");
        builder.Property(x => x.LocationCode).HasColumnName("location_code");
        builder.Property(x => x.ShortcutDimension1Code).HasColumnName("shortcut_dimension_1_code");
        builder.Property(x => x.ShortcutDimension2Code).HasColumnName("shortcut_dimension_2_code");
        builder.Property(x => x.CustomerPostingGroup).HasColumnName("customer_posting_group");
        builder.Property(x => x.CurrencyCode).HasColumnName("currency_code");
        builder.Property(x => x.CurrencyFactor).HasColumnName("currency_factor").HasPrecision(18, 5);
        builder.Property(x => x.CustomerPriceGroup).HasColumnName("customer_price_group");
        builder.Property(x => x.PricesIncludingVat).HasColumnName("prices_including_vat");
        builder.Property(x => x.InvoiceDiscCode).HasColumnName("invoice_disc_code");
        builder.Property(x => x.CustomerDiscGroup).HasColumnName("customer_disc_group");
        builder.Property(x => x.LanguageCode).HasColumnName("language_code");
        builder.Property(x => x.SalespersonCode).HasColumnName("salesperson_code");
        builder.Property(x => x.NoPrinted).HasColumnName("no_printed");
        builder.Property(x => x.AppliesToDocType).HasColumnName("applies_to_doc_type");
        builder.Property(x => x.AppliesToDocNo).HasColumnName("applies_to_doc_no");
        builder.Property(x => x.BalAccountNo).HasColumnName("bal_account_no");
        builder.Property(x => x.ShippingNo).HasColumnName("shipping_no");
        builder.Property(x => x.PostingNo).HasColumnName("posting_no");
        builder.Property(x => x.LastShippingNo).HasColumnName("last_shipping_no");
        builder.Property(x => x.LastPostingNo).HasColumnName("last_posting_no");
        builder.Property(x => x.VatRegistrationNo).HasColumnName("vat_registration_no");
        builder.Property(x => x.ReasonCode).HasColumnName("reason_code");
        builder.Property(x => x.GenBusPostingGroup).HasColumnName("gen_bus_posting_group");
        builder.Property(x => x.Eu3PartyTrade).HasColumnName("eu_3_party_trade");
        builder.Property(x => x.TransactionType).HasColumnName("transaction_type");
        builder.Property(x => x.TransportMethod).HasColumnName("transport_method");
        builder.Property(x => x.VatCountryRegionCode).HasColumnName("vat_country_region_code");
        builder.Property(x => x.Name).HasColumnName("name");
        builder.Property(x => x.Name2).HasColumnName("name_2");
        builder.Property(x => x.Address).HasColumnName("address");
        builder.Property(x => x.Address2).HasColumnName("address_2");
        builder.Property(x => x.City).HasColumnName("city");
        builder.Property(x => x.ContactName).HasColumnName("contact_name");
        builder.Property(x => x.BillToPostCode).HasColumnName("bill_to_post_code");
        builder.Property(x => x.BillToCounty).HasColumnName("bill_to_county");
        builder.Property(x => x.BillToCountryRegionCode).HasColumnName("bill_to_country_region_code");
        builder.Property(x => x.PostCode).HasColumnName("post_code");
        builder.Property(x => x.County).HasColumnName("county");
        builder.Property(x => x.CountryRegionCode).HasColumnName("country_region_code");
        builder.Property(x => x.ShipToPostCode).HasColumnName("ship_to_post_code");
        builder.Property(x => x.ShipToCounty).HasColumnName("ship_to_county");
        builder.Property(x => x.ShipToCountryRegionCode).HasColumnName("ship_to_country_region_code");
        builder.Property(x => x.BalAccountType).HasColumnName("bal_account_type");
        builder.Property(x => x.ExitPoint).HasColumnName("exit_point");
        builder.Property(x => x.Correction).HasColumnName("correction");
        builder.Property(x => x.DocumentDate).HasColumnName("document_date");
        builder.Property(x => x.Area).HasColumnName("area");
        builder.Property(x => x.TransactionSpecification).HasColumnName("transaction_specification");
        builder.Property(x => x.PaymentMethodCode).HasColumnName("payment_method_code");
        builder.Property(x => x.ShippingAgentCode).HasColumnName("shipping_agent_code");
        builder.Property(x => x.NoSeries).HasColumnName("no_series");
        builder.Property(x => x.PostingNoSeries).HasColumnName("posting_no_series");
        builder.Property(x => x.ShippingNoSeries).HasColumnName("shipping_no_series");
        builder.Property(x => x.TaxAreaCode).HasColumnName("tax_area_code");
        builder.Property(x => x.TaxLiable).HasColumnName("tax_liable");
        builder.Property(x => x.VatBusPostingGroup).HasColumnName("vat_bus_posting_group");
        builder.Property(x => x.Reserve).HasColumnName("reserve");
        builder.Property(x => x.AppliesToId).HasColumnName("applies_to_id");
        builder.Property(x => x.VatBaseDiscount).HasColumnName("vat_base_discount").HasPrecision(18, 5);
        builder.Property(x => x.Status).HasColumnName("status");
        builder.Property(x => x.InvoiceDiscountCalculation).HasColumnName("invoice_discount_calculation");
        builder.Property(x => x.InvoiceDiscountValue).HasColumnName("invoice_discount_value").HasPrecision(18, 5);
        builder.Property(x => x.ReleaseStatus).HasColumnName("release_status");
        builder.Property(x => x.DimensionSetId).HasColumnName("dimension_set_id");
        builder.Property(x => x.ContactNo).HasColumnName("contact_no");
        builder.Property(x => x.BillToContactNo).HasColumnName("bill_to_contact_no");
        builder.Property(x => x.ResponsibilityCenter).HasColumnName("responsibility_center");
        builder.Property(x => x.ShippingAdvice).HasColumnName("shipping_advice");
        builder.Property(x => x.ShippingTime).HasColumnName("shipping_time");
        builder.Property(x => x.ShippingAgentServiceCode).HasColumnName("shipping_agent_service_code");
        builder.Property(x => x.Description).HasColumnName("description");
        builder.Property(x => x.ServiceOrderType).HasColumnName("service_order_type");
        builder.Property(x => x.LinkServiceToServiceItem).HasColumnName("link_service_to_service_item");
        builder.Property(x => x.Priority).HasColumnName("priority");
        builder.Property(x => x.PhoneNo).HasColumnName("phone_no");
        builder.Property(x => x.EMail).HasColumnName("e_mail");
        builder.Property(x => x.PhoneNo2).HasColumnName("phone_no_2");
        builder.Property(x => x.FaxNo).HasColumnName("fax_no");
        builder.Property(x => x.OrderTime).HasColumnName("order_time");
        builder.Property(x => x.DefaultResponseTimeHours).HasColumnName("default_response_time_hours").HasPrecision(18, 5);
        builder.Property(x => x.ActualResponseTimeHours).HasColumnName("actual_response_time_hours").HasPrecision(18, 5);
        builder.Property(x => x.ServiceTimeHours).HasColumnName("service_time_hours").HasPrecision(18, 5);
        builder.Property(x => x.ResponseDate).HasColumnName("response_date");
        builder.Property(x => x.ResponseTime).HasColumnName("response_time");
        builder.Property(x => x.StartingDate).HasColumnName("starting_date");
        builder.Property(x => x.StartingTime).HasColumnName("starting_time");
        builder.Property(x => x.FinishingDate).HasColumnName("finishing_date");
        builder.Property(x => x.FinishingTime).HasColumnName("finishing_time");
        builder.Property(x => x.NotifyCustomer).HasColumnName("notify_customer");
        builder.Property(x => x.MaxLaborUnitPrice).HasColumnName("max_labor_unit_price").HasPrecision(18, 5);
        builder.Property(x => x.WarningStatus).HasColumnName("warning_status");
        builder.Property(x => x.ContractNo).HasColumnName("contract_no");
        builder.Property(x => x.ShipToFaxNo).HasColumnName("ship_to_fax_no");
        builder.Property(x => x.ShipToEMail).HasColumnName("ship_to_e_mail");
        builder.Property(x => x.ShipToPhone).HasColumnName("ship_to_phone");
        builder.Property(x => x.ShipToPhone2).HasColumnName("ship_to_phone_2");
        builder.Property(x => x.ServiceZoneCode).HasColumnName("service_zone_code");
        builder.Property(x => x.ExpectedFinishingDate).HasColumnName("expected_finishing_date");
        builder.Property(x => x.AllowLineDisc).HasColumnName("allow_line_disc");
        builder.Property(x => x.AssignedUserId).HasColumnName("assigned_user_id");
        builder.Property(x => x.QuoteNo).HasColumnName("quote_no");
    }
}
