using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Metadata.Builders;
using NexusBilling.Core.Domain.Common;
using NexusBilling.Core.Domain.Administration.Entities;

namespace NexusBilling.Infrastructure.Persistence.Administration.Configurations;

public class ServiceShipmentLineConfiguration : IEntityTypeConfiguration<ServiceShipmentLine>
{
    public void Configure(EntityTypeBuilder<ServiceShipmentLine> builder)
    {
        builder.ToTable("service_shipment_line", "administration");
        builder.HasKey(x => x.Id);
        builder.Property(x => x.TenantId).HasConversion(v => v.Value, v => TenantIdentifier.Create(v)).HasColumnName("tenant_id").IsRequired();
        builder.Property(x => x.CustomerNo).HasColumnName("customer_no");
        builder.Property(x => x.DocumentNo).HasColumnName("document_no");
        builder.Property(x => x.LineNo).HasColumnName("line_no");
        builder.Property(x => x.Type).HasColumnName("type");
        builder.Property(x => x.No).HasColumnName("no");
        builder.Property(x => x.LocationCode).HasColumnName("location_code");
        builder.Property(x => x.PostingGroup).HasColumnName("posting_group");
        builder.Property(x => x.Description).HasColumnName("description");
        builder.Property(x => x.Description2).HasColumnName("description_2");
        builder.Property(x => x.UnitOfMeasure).HasColumnName("unit_of_measure");
        builder.Property(x => x.Quantity).HasColumnName("quantity").HasPrecision(18, 5);
        builder.Property(x => x.UnitPrice).HasColumnName("unit_price").HasPrecision(18, 5);
        builder.Property(x => x.UnitCostLcy).HasColumnName("unit_cost_lcy").HasPrecision(18, 5);
        builder.Property(x => x.Vat).HasColumnName("vat").HasPrecision(18, 5);
        builder.Property(x => x.LineDiscount).HasColumnName("line_discount").HasPrecision(18, 5);
        builder.Property(x => x.AllowInvoiceDisc).HasColumnName("allow_invoice_disc");
        builder.Property(x => x.GrossWeight).HasColumnName("gross_weight").HasPrecision(18, 5);
        builder.Property(x => x.NetWeight).HasColumnName("net_weight").HasPrecision(18, 5);
        builder.Property(x => x.UnitsPerParcel).HasColumnName("units_per_parcel").HasPrecision(18, 5);
        builder.Property(x => x.UnitVolume).HasColumnName("unit_volume").HasPrecision(18, 5);
        builder.Property(x => x.ApplToItemEntry).HasColumnName("appl_to_item_entry");
        builder.Property(x => x.ItemShptEntryNo).HasColumnName("item_shpt_entry_no");
        builder.Property(x => x.ShortcutDimension1Code).HasColumnName("shortcut_dimension_1_code");
        builder.Property(x => x.ShortcutDimension2Code).HasColumnName("shortcut_dimension_2_code");
        builder.Property(x => x.CustomerPriceGroup).HasColumnName("customer_price_group");
        builder.Property(x => x.WorkTypeCode).HasColumnName("work_type_code");
        builder.Property(x => x.QtyShippedNotInvoiced).HasColumnName("qty_shipped_not_invoiced").HasPrecision(18, 5);
        builder.Property(x => x.QuantityInvoiced).HasColumnName("quantity_invoiced").HasPrecision(18, 5);
        builder.Property(x => x.OrderNo).HasColumnName("order_no");
        builder.Property(x => x.OrderLineNo).HasColumnName("order_line_no");
        builder.Property(x => x.BillToCustomerNo).HasColumnName("bill_to_customer_no");
        builder.Property(x => x.GenBusPostingGroup).HasColumnName("gen_bus_posting_group");
        builder.Property(x => x.GenProdPostingGroup).HasColumnName("gen_prod_posting_group");
        builder.Property(x => x.VatCalculationType).HasColumnName("vat_calculation_type");
        builder.Property(x => x.TransactionType).HasColumnName("transaction_type");
        builder.Property(x => x.TransportMethod).HasColumnName("transport_method");
        builder.Property(x => x.AttachedToLineNo).HasColumnName("attached_to_line_no");
        builder.Property(x => x.ExitPoint).HasColumnName("exit_point");
        builder.Property(x => x.Area).HasColumnName("area");
        builder.Property(x => x.TransactionSpecification).HasColumnName("transaction_specification");
        builder.Property(x => x.TaxAreaCode).HasColumnName("tax_area_code");
        builder.Property(x => x.TaxLiable).HasColumnName("tax_liable");
        builder.Property(x => x.TaxGroupCode).HasColumnName("tax_group_code");
        builder.Property(x => x.VatBusPostingGroup).HasColumnName("vat_bus_posting_group");
        builder.Property(x => x.VatProdPostingGroup).HasColumnName("vat_prod_posting_group");
        builder.Property(x => x.CurrencyCode).HasColumnName("currency_code");
        builder.Property(x => x.VatBaseAmount).HasColumnName("vat_base_amount").HasPrecision(18, 5);
        builder.Property(x => x.UnitCost).HasColumnName("unit_cost").HasPrecision(18, 5);
        builder.Property(x => x.DimensionSetId).HasColumnName("dimension_set_id");
        builder.Property(x => x.TimeSheetNo).HasColumnName("time_sheet_no");
        builder.Property(x => x.TimeSheetLineNo).HasColumnName("time_sheet_line_no");
        builder.Property(x => x.TimeSheetDate).HasColumnName("time_sheet_date");
        builder.Property(x => x.VariantCode).HasColumnName("variant_code");
        builder.Property(x => x.BinCode).HasColumnName("bin_code");
        builder.Property(x => x.QtyPerUnitOfMeasure).HasColumnName("qty_per_unit_of_measure").HasPrecision(18, 5);
        builder.Property(x => x.UnitOfMeasureCode).HasColumnName("unit_of_measure_code");
        builder.Property(x => x.QuantityBase).HasColumnName("quantity_base").HasPrecision(18, 5);
        builder.Property(x => x.QtyShippedNotInvdBase).HasColumnName("qty_shipped_not_invd_base").HasPrecision(18, 5);
        builder.Property(x => x.QtyInvoicedBase).HasColumnName("qty_invoiced_base").HasPrecision(18, 5);
        builder.Property(x => x.ResponsibilityCenter).HasColumnName("responsibility_center");
        builder.Property(x => x.ItemCategoryCode).HasColumnName("item_category_code");
        builder.Property(x => x.Nonstock).HasColumnName("nonstock");
        builder.Property(x => x.ProductGroupCode).HasColumnName("product_group_code");
        builder.Property(x => x.Correction).HasColumnName("correction");
        builder.Property(x => x.ApplToWarrantyEntry).HasColumnName("appl_to_warranty_entry");
        builder.Property(x => x.ServiceItemNo).HasColumnName("service_item_no");
        builder.Property(x => x.ApplToServiceEntry).HasColumnName("appl_to_service_entry");
        builder.Property(x => x.ServiceItemLineNo).HasColumnName("service_item_line_no");
        builder.Property(x => x.ServiceItemSerialNo).HasColumnName("service_item_serial_no");
        builder.Property(x => x.ServiceItemLineDescription).HasColumnName("service_item_line_description");
        builder.Property(x => x.PostingDate).HasColumnName("posting_date");
        builder.Property(x => x.OrderDate).HasColumnName("order_date");
        builder.Property(x => x.NeededByDate).HasColumnName("needed_by_date");
        builder.Property(x => x.ShipToCode).HasColumnName("ship_to_code");
        builder.Property(x => x.QuantityConsumed).HasColumnName("quantity_consumed").HasPrecision(18, 5);
        builder.Property(x => x.QtyConsumedBase).HasColumnName("qty_consumed_base").HasPrecision(18, 5);
        builder.Property(x => x.ServicePriceGroupCode).HasColumnName("service_price_group_code");
        builder.Property(x => x.FaultAreaCode).HasColumnName("fault_area_code");
        builder.Property(x => x.SymptomCode).HasColumnName("symptom_code");
        builder.Property(x => x.FaultCode).HasColumnName("fault_code");
        builder.Property(x => x.ResolutionCode).HasColumnName("resolution_code");
        builder.Property(x => x.ExcludeWarranty).HasColumnName("exclude_warranty");
        builder.Property(x => x.Warranty).HasColumnName("warranty");
        builder.Property(x => x.ContractNo).HasColumnName("contract_no");
        builder.Property(x => x.ContractDisc).HasColumnName("contract_disc").HasPrecision(18, 5);
        builder.Property(x => x.WarrantyDisc).HasColumnName("warranty_disc").HasPrecision(18, 5);
        builder.Property(x => x.ComponentLineNo).HasColumnName("component_line_no");
        builder.Property(x => x.SparePartAction).HasColumnName("spare_part_action");
        builder.Property(x => x.FaultReasonCode).HasColumnName("fault_reason_code");
        builder.Property(x => x.ReplacedItemNo).HasColumnName("replaced_item_no");
        builder.Property(x => x.ExcludeContractDiscount).HasColumnName("exclude_contract_discount");
        builder.Property(x => x.ReplacedItemType).HasColumnName("replaced_item_type");
        builder.Property(x => x.PriceAdjmtStatus).HasColumnName("price_adjmt_status");
        builder.Property(x => x.LineDiscountType).HasColumnName("line_discount_type");
        builder.Property(x => x.CopyComponentsFrom).HasColumnName("copy_components_from");
        builder.Property(x => x.ReturnReasonCode).HasColumnName("return_reason_code");
        builder.Property(x => x.AllowLineDisc).HasColumnName("allow_line_disc");
        builder.Property(x => x.CustomerDiscGroup).HasColumnName("customer_disc_group");
    }
}
