using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Metadata.Builders;
using NexusBilling.Core.Domain.Common;
using NexusBilling.Core.Domain.Sales.Entities;

namespace NexusBilling.Infrastructure.Persistence.Sales.Configurations;

public class SalesShipmentLineConfiguration : IEntityTypeConfiguration<SalesShipmentLine>
{
    public void Configure(EntityTypeBuilder<SalesShipmentLine> builder)
    {
        builder.ToTable("sales_shipment_line", "sales");
        builder.HasKey(x => x.Id);
        builder.Property(x => x.TenantId).HasConversion(v => v.Value, v => TenantIdentifier.Create(v)).HasColumnName("tenant_id").IsRequired();
        builder.Property(x => x.SellToCustomerNo).HasColumnName("sell_to_customer_no");
        builder.Property(x => x.DocumentNo).HasColumnName("document_no");
        builder.Property(x => x.LineNo).HasColumnName("line_no");
        builder.Property(x => x.Type).HasColumnName("type");
        builder.Property(x => x.No).HasColumnName("no");
        builder.Property(x => x.LocationCode).HasColumnName("location_code");
        builder.Property(x => x.PostingGroup).HasColumnName("posting_group");
        builder.Property(x => x.ShipmentDate).HasColumnName("shipment_date");
        builder.Property(x => x.Description).HasColumnName("description");
        builder.Property(x => x.Description2).HasColumnName("description_2");
        builder.Property(x => x.UnitOfMeasure).HasColumnName("unit_of_measure");
        builder.Property(x => x.Quantity).HasColumnName("quantity").HasPrecision(18, 5);
        builder.Property(x => x.UnitPrice).HasColumnName("unit_price").HasPrecision(18, 5);
        builder.Property(x => x.UnitCostLcy).HasColumnName("unit_cost_lcy").HasPrecision(18, 5);
        builder.Property(x => x.Vat).HasColumnName("vat").HasPrecision(18, 5);
        builder.Property(x => x.LineDiscount).HasColumnName("line_discount").HasPrecision(18, 5);
        builder.Property(x => x.AllowInvoiceDisc).HasColumnName("allow_invoice_disc");
        builder.Property(x => x.GrossWeight).HasColumnName("gross_weight").HasPrecision(18, 5);
        builder.Property(x => x.NetWeight).HasColumnName("net_weight").HasPrecision(18, 5);
        builder.Property(x => x.UnitsPerParcel).HasColumnName("units_per_parcel").HasPrecision(18, 5);
        builder.Property(x => x.UnitVolume).HasColumnName("unit_volume").HasPrecision(18, 5);
        builder.Property(x => x.ApplToItemEntry).HasColumnName("appl_to_item_entry");
        builder.Property(x => x.ItemShptEntryNo).HasColumnName("item_shpt_entry_no");
        builder.Property(x => x.ShortcutDimension1Code).HasColumnName("shortcut_dimension_1_code");
        builder.Property(x => x.ShortcutDimension2Code).HasColumnName("shortcut_dimension_2_code");
        builder.Property(x => x.CustomerPriceGroup).HasColumnName("customer_price_group");
        builder.Property(x => x.JobNo).HasColumnName("job_no");
        builder.Property(x => x.WorkTypeCode).HasColumnName("work_type_code");
        builder.Property(x => x.QtyShippedNotInvoiced).HasColumnName("qty_shipped_not_invoiced").HasPrecision(18, 5);
        builder.Property(x => x.QuantityInvoiced).HasColumnName("quantity_invoiced").HasPrecision(18, 5);
        builder.Property(x => x.OrderNo).HasColumnName("order_no");
        builder.Property(x => x.OrderLineNo).HasColumnName("order_line_no");
        builder.Property(x => x.BillToCustomerNo).HasColumnName("bill_to_customer_no");
        builder.Property(x => x.PurchaseOrderNo).HasColumnName("purchase_order_no");
        builder.Property(x => x.PurchOrderLineNo).HasColumnName("purch_order_line_no");
        builder.Property(x => x.DropShipment).HasColumnName("drop_shipment");
        builder.Property(x => x.GenBusPostingGroup).HasColumnName("gen_bus_posting_group");
        builder.Property(x => x.GenProdPostingGroup).HasColumnName("gen_prod_posting_group");
        builder.Property(x => x.VatCalculationType).HasColumnName("vat_calculation_type");
        builder.Property(x => x.TransactionType).HasColumnName("transaction_type");
        builder.Property(x => x.TransportMethod).HasColumnName("transport_method");
        builder.Property(x => x.AttachedToLineNo).HasColumnName("attached_to_line_no");
        builder.Property(x => x.ExitPoint).HasColumnName("exit_point");
        builder.Property(x => x.Area).HasColumnName("area");
        builder.Property(x => x.TransactionSpecification).HasColumnName("transaction_specification");
        builder.Property(x => x.TaxAreaCode).HasColumnName("tax_area_code");
        builder.Property(x => x.TaxLiable).HasColumnName("tax_liable");
        builder.Property(x => x.TaxGroupCode).HasColumnName("tax_group_code");
        builder.Property(x => x.VatBusPostingGroup).HasColumnName("vat_bus_posting_group");
        builder.Property(x => x.VatProdPostingGroup).HasColumnName("vat_prod_posting_group");
        builder.Property(x => x.BlanketOrderNo).HasColumnName("blanket_order_no");
        builder.Property(x => x.BlanketOrderLineNo).HasColumnName("blanket_order_line_no");
        builder.Property(x => x.VatBaseAmount).HasColumnName("vat_base_amount").HasPrecision(18, 5);
        builder.Property(x => x.UnitCost).HasColumnName("unit_cost").HasPrecision(18, 5);
        builder.Property(x => x.PostingDate).HasColumnName("posting_date");
        builder.Property(x => x.DimensionSetId).HasColumnName("dimension_set_id");
        builder.Property(x => x.AuthorizedForCreditCard).HasColumnName("authorized_for_credit_card");
        builder.Property(x => x.JobTaskNo).HasColumnName("job_task_no");
        builder.Property(x => x.JobContractEntryNo).HasColumnName("job_contract_entry_no");
        builder.Property(x => x.VariantCode).HasColumnName("variant_code");
        builder.Property(x => x.BinCode).HasColumnName("bin_code");
        builder.Property(x => x.QtyPerUnitOfMeasure).HasColumnName("qty_per_unit_of_measure").HasPrecision(18, 5);
        builder.Property(x => x.UnitOfMeasureCode).HasColumnName("unit_of_measure_code");
        builder.Property(x => x.QuantityBase).HasColumnName("quantity_base").HasPrecision(18, 5);
        builder.Property(x => x.QtyInvoicedBase).HasColumnName("qty_invoiced_base").HasPrecision(18, 5);
        builder.Property(x => x.FaPostingDate).HasColumnName("fa_posting_date");
        builder.Property(x => x.DepreciationBookCode).HasColumnName("depreciation_book_code");
        builder.Property(x => x.DeprUntilFaPostingDate).HasColumnName("depr_until_fa_posting_date");
        builder.Property(x => x.DuplicateInDepreciationBook).HasColumnName("duplicate_in_depreciation_book");
        builder.Property(x => x.UseDuplicationList).HasColumnName("use_duplication_list");
        builder.Property(x => x.ResponsibilityCenter).HasColumnName("responsibility_center");
        builder.Property(x => x.CrossReferenceNo).HasColumnName("cross_reference_no");
        builder.Property(x => x.UnitOfMeasureCrossRef).HasColumnName("unit_of_measure_cross_ref");
        builder.Property(x => x.CrossReferenceType).HasColumnName("cross_reference_type");
        builder.Property(x => x.CrossReferenceTypeNo).HasColumnName("cross_reference_type_no");
        builder.Property(x => x.ItemCategoryCode).HasColumnName("item_category_code");
        builder.Property(x => x.Nonstock).HasColumnName("nonstock");
        builder.Property(x => x.PurchasingCode).HasColumnName("purchasing_code");
        builder.Property(x => x.ProductGroupCode).HasColumnName("product_group_code");
        builder.Property(x => x.RequestedDeliveryDate).HasColumnName("requested_delivery_date");
        builder.Property(x => x.PromisedDeliveryDate).HasColumnName("promised_delivery_date");
        builder.Property(x => x.ShippingTime).HasColumnName("shipping_time");
        builder.Property(x => x.OutboundWhseHandlingTime).HasColumnName("outbound_whse_handling_time");
        builder.Property(x => x.PlannedDeliveryDate).HasColumnName("planned_delivery_date");
        builder.Property(x => x.PlannedShipmentDate).HasColumnName("planned_shipment_date");
        builder.Property(x => x.ApplFromItemEntry).HasColumnName("appl_from_item_entry");
        builder.Property(x => x.ItemChargeBaseAmount).HasColumnName("item_charge_base_amount").HasPrecision(18, 5);
        builder.Property(x => x.Correction).HasColumnName("correction");
        builder.Property(x => x.ReturnReasonCode).HasColumnName("return_reason_code");
        builder.Property(x => x.AllowLineDisc).HasColumnName("allow_line_disc");
        builder.Property(x => x.CustomerDiscGroup).HasColumnName("customer_disc_group");
    }
}
