using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Metadata.Builders;
using NexusBilling.Core.Domain.Common;
using NexusBilling.Core.Domain.Sales.Entities;

namespace NexusBilling.Infrastructure.Persistence.Sales.Configurations;

public class SalesShipmentHeaderConfiguration : IEntityTypeConfiguration<SalesShipmentHeader>
{
    public void Configure(EntityTypeBuilder<SalesShipmentHeader> builder)
    {
        builder.ToTable("sales_shipment_header", "sales");
        builder.HasKey(x => x.Id);
        builder.Property(x => x.TenantId).HasConversion(v => v.Value, v => TenantIdentifier.Create(v)).HasColumnName("tenant_id").IsRequired();
        builder.Property(x => x.SellToCustomerNo).HasColumnName("sell_to_customer_no");
        builder.Property(x => x.No).HasColumnName("no");
        builder.Property(x => x.BillToCustomerNo).HasColumnName("bill_to_customer_no");
        builder.Property(x => x.BillToName).HasColumnName("bill_to_name");
        builder.Property(x => x.BillToName2).HasColumnName("bill_to_name_2");
        builder.Property(x => x.BillToAddress).HasColumnName("bill_to_address");
        builder.Property(x => x.BillToAddress2).HasColumnName("bill_to_address_2");
        builder.Property(x => x.BillToCity).HasColumnName("bill_to_city");
        builder.Property(x => x.BillToContact).HasColumnName("bill_to_contact");
        builder.Property(x => x.YourReference).HasColumnName("your_reference");
        builder.Property(x => x.ShipToCode).HasColumnName("ship_to_code");
        builder.Property(x => x.ShipToName).HasColumnName("ship_to_name");
        builder.Property(x => x.ShipToName2).HasColumnName("ship_to_name_2");
        builder.Property(x => x.ShipToAddress).HasColumnName("ship_to_address");
        builder.Property(x => x.ShipToAddress2).HasColumnName("ship_to_address_2");
        builder.Property(x => x.ShipToCity).HasColumnName("ship_to_city");
        builder.Property(x => x.ShipToContact).HasColumnName("ship_to_contact");
        builder.Property(x => x.OrderDate).HasColumnName("order_date");
        builder.Property(x => x.PostingDate).HasColumnName("posting_date");
        builder.Property(x => x.ShipmentDate).HasColumnName("shipment_date");
        builder.Property(x => x.PostingDescription).HasColumnName("posting_description");
        builder.Property(x => x.PaymentTermsCode).HasColumnName("payment_terms_code");
        builder.Property(x => x.DueDate).HasColumnName("due_date");
        builder.Property(x => x.PaymentDiscount).HasColumnName("payment_discount").HasPrecision(18, 5);
        builder.Property(x => x.PmtDiscountDate).HasColumnName("pmt_discount_date");
        builder.Property(x => x.ShipmentMethodCode).HasColumnName("shipment_method_code");
        builder.Property(x => x.LocationCode).HasColumnName("location_code");
        builder.Property(x => x.ShortcutDimension1Code).HasColumnName("shortcut_dimension_1_code");
        builder.Property(x => x.ShortcutDimension2Code).HasColumnName("shortcut_dimension_2_code");
        builder.Property(x => x.CustomerPostingGroup).HasColumnName("customer_posting_group");
        builder.Property(x => x.CurrencyCode).HasColumnName("currency_code");
        builder.Property(x => x.CurrencyFactor).HasColumnName("currency_factor").HasPrecision(18, 5);
        builder.Property(x => x.CustomerPriceGroup).HasColumnName("customer_price_group");
        builder.Property(x => x.PricesIncludingVat).HasColumnName("prices_including_vat");
        builder.Property(x => x.InvoiceDiscCode).HasColumnName("invoice_disc_code");
        builder.Property(x => x.CustomerDiscGroup).HasColumnName("customer_disc_group");
        builder.Property(x => x.LanguageCode).HasColumnName("language_code");
        builder.Property(x => x.SalespersonCode).HasColumnName("salesperson_code");
        builder.Property(x => x.OrderNo).HasColumnName("order_no");
        builder.Property(x => x.NoPrinted).HasColumnName("no_printed");
        builder.Property(x => x.OnHold).HasColumnName("on_hold");
        builder.Property(x => x.AppliesToDocType).HasColumnName("applies_to_doc_type");
        builder.Property(x => x.AppliesToDocNo).HasColumnName("applies_to_doc_no");
        builder.Property(x => x.BalAccountNo).HasColumnName("bal_account_no");
        builder.Property(x => x.VatRegistrationNo).HasColumnName("vat_registration_no");
        builder.Property(x => x.ReasonCode).HasColumnName("reason_code");
        builder.Property(x => x.GenBusPostingGroup).HasColumnName("gen_bus_posting_group");
        builder.Property(x => x.Eu3PartyTrade).HasColumnName("eu_3_party_trade");
        builder.Property(x => x.TransactionType).HasColumnName("transaction_type");
        builder.Property(x => x.TransportMethod).HasColumnName("transport_method");
        builder.Property(x => x.VatCountryRegionCode).HasColumnName("vat_country_region_code");
        builder.Property(x => x.SellToCustomerName).HasColumnName("sell_to_customer_name");
        builder.Property(x => x.SellToCustomerName2).HasColumnName("sell_to_customer_name_2");
        builder.Property(x => x.SellToAddress).HasColumnName("sell_to_address");
        builder.Property(x => x.SellToAddress2).HasColumnName("sell_to_address_2");
        builder.Property(x => x.SellToCity).HasColumnName("sell_to_city");
        builder.Property(x => x.SellToContact).HasColumnName("sell_to_contact");
        builder.Property(x => x.BillToPostCode).HasColumnName("bill_to_post_code");
        builder.Property(x => x.BillToCounty).HasColumnName("bill_to_county");
        builder.Property(x => x.BillToCountryRegionCode).HasColumnName("bill_to_country_region_code");
        builder.Property(x => x.SellToPostCode).HasColumnName("sell_to_post_code");
        builder.Property(x => x.SellToCounty).HasColumnName("sell_to_county");
        builder.Property(x => x.SellToCountryRegionCode).HasColumnName("sell_to_country_region_code");
        builder.Property(x => x.ShipToPostCode).HasColumnName("ship_to_post_code");
        builder.Property(x => x.ShipToCounty).HasColumnName("ship_to_county");
        builder.Property(x => x.ShipToCountryRegionCode).HasColumnName("ship_to_country_region_code");
        builder.Property(x => x.BalAccountType).HasColumnName("bal_account_type");
        builder.Property(x => x.ExitPoint).HasColumnName("exit_point");
        builder.Property(x => x.Correction).HasColumnName("correction");
        builder.Property(x => x.DocumentDate).HasColumnName("document_date");
        builder.Property(x => x.ExternalDocumentNo).HasColumnName("external_document_no");
        builder.Property(x => x.Area).HasColumnName("area");
        builder.Property(x => x.TransactionSpecification).HasColumnName("transaction_specification");
        builder.Property(x => x.PaymentMethodCode).HasColumnName("payment_method_code");
        builder.Property(x => x.ShippingAgentCode).HasColumnName("shipping_agent_code");
        builder.Property(x => x.PackageTrackingNo).HasColumnName("package_tracking_no");
        builder.Property(x => x.NoSeries).HasColumnName("no_series");
        builder.Property(x => x.OrderNoSeries).HasColumnName("order_no_series");
        builder.Property(x => x.UserId).HasColumnName("user_id");
        builder.Property(x => x.SourceCode).HasColumnName("source_code");
        builder.Property(x => x.TaxAreaCode).HasColumnName("tax_area_code");
        builder.Property(x => x.TaxLiable).HasColumnName("tax_liable");
        builder.Property(x => x.VatBusPostingGroup).HasColumnName("vat_bus_posting_group");
        builder.Property(x => x.VatBaseDiscount).HasColumnName("vat_base_discount").HasPrecision(18, 5);
        builder.Property(x => x.QuoteNo).HasColumnName("quote_no");
        builder.Property(x => x.DimensionSetId).HasColumnName("dimension_set_id");
        builder.Property(x => x.CampaignNo).HasColumnName("campaign_no");
        builder.Property(x => x.SellToContactNo).HasColumnName("sell_to_contact_no");
        builder.Property(x => x.BillToContactNo).HasColumnName("bill_to_contact_no");
        builder.Property(x => x.OpportunityNo).HasColumnName("opportunity_no");
        builder.Property(x => x.ResponsibilityCenter).HasColumnName("responsibility_center");
        builder.Property(x => x.RequestedDeliveryDate).HasColumnName("requested_delivery_date");
        builder.Property(x => x.PromisedDeliveryDate).HasColumnName("promised_delivery_date");
        builder.Property(x => x.ShippingTime).HasColumnName("shipping_time");
        builder.Property(x => x.OutboundWhseHandlingTime).HasColumnName("outbound_whse_handling_time");
        builder.Property(x => x.ShippingAgentServiceCode).HasColumnName("shipping_agent_service_code");
        builder.Property(x => x.AllowLineDisc).HasColumnName("allow_line_disc");
    }
}
