<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <Folder Include="Migrations\" />
    <Folder Include="Context\" />
    <Folder Include="EntityConfigurations\" />
    <Folder Include="Repositories\" />
    <Folder Include="Repositories\base\" />
  </ItemGroup>

  <ItemGroup>
  <!-- EF Core -->
    <PackageReference Include="Microsoft.EntityFrameworkCore" Version="8.0.2" />
    <PackageReference Include="Microsoft.EntityFrameworkCore.Relational" Version="8.0.2" />

    <!-- MySQL Provider -->
    <PackageReference Include="Pomelo.EntityFrameworkCore.MySql" Version="8.0.2" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\nexus_bilding_api.core.domain\nexus_bilding_api.core.domain.csproj" />
  </ItemGroup>

</Project>
