using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Metadata.Builders;
using NexusBilling.Core.Domain.Common;
using NexusBilling.Core.Domain.Purchasing.Entities;

namespace NexusBilling.Infrastructure.Persistence.Purchasing.Configurations;

public class PurchRcptLineConfiguration : IEntityTypeConfiguration<PurchRcptLine>
{
    public void Configure(EntityTypeBuilder<PurchRcptLine> builder)
    {
        builder.ToTable("purch_rcpt_line", "purchasing");
        builder.HasKey(x => x.Id);
        builder.Property(x => x.TenantId).HasConversion(v => v.Value, v => TenantIdentifier.Create(v)).HasColumnName("tenant_id").IsRequired();
        builder.Property(x => x.BuyFromVendorNo).HasColumnName("buy_from_vendor_no");
        builder.Property(x => x.DocumentNo).HasColumnName("document_no");
        builder.Property(x => x.LineNo).HasColumnName("line_no");
        builder.Property(x => x.Type).HasColumnName("type");
        builder.Property(x => x.No).HasColumnName("no");
        builder.Property(x => x.LocationCode).HasColumnName("location_code");
        builder.Property(x => x.PostingGroup).HasColumnName("posting_group");
        builder.Property(x => x.ExpectedReceiptDate).HasColumnName("expected_receipt_date");
        builder.Property(x => x.Description).HasColumnName("description");
        builder.Property(x => x.Description2).HasColumnName("description_2");
        builder.Property(x => x.UnitOfMeasure).HasColumnName("unit_of_measure");
        builder.Property(x => x.Quantity).HasColumnName("quantity").HasPrecision(18, 5);
        builder.Property(x => x.DirectUnitCost).HasColumnName("direct_unit_cost").HasPrecision(18, 5);
        builder.Property(x => x.UnitCostLcy).HasColumnName("unit_cost_lcy").HasPrecision(18, 5);
        builder.Property(x => x.Vat).HasColumnName("vat").HasPrecision(18, 5);
        builder.Property(x => x.LineDiscount).HasColumnName("line_discount").HasPrecision(18, 5);
        builder.Property(x => x.UnitPriceLcy).HasColumnName("unit_price_lcy").HasPrecision(18, 5);
        builder.Property(x => x.AllowInvoiceDisc).HasColumnName("allow_invoice_disc");
        builder.Property(x => x.GrossWeight).HasColumnName("gross_weight").HasPrecision(18, 5);
        builder.Property(x => x.NetWeight).HasColumnName("net_weight").HasPrecision(18, 5);
        builder.Property(x => x.UnitsPerParcel).HasColumnName("units_per_parcel").HasPrecision(18, 5);
        builder.Property(x => x.UnitVolume).HasColumnName("unit_volume").HasPrecision(18, 5);
        builder.Property(x => x.ApplToItemEntry).HasColumnName("appl_to_item_entry");
        builder.Property(x => x.ItemRcptEntryNo).HasColumnName("item_rcpt_entry_no");
        builder.Property(x => x.ShortcutDimension1Code).HasColumnName("shortcut_dimension_1_code");
        builder.Property(x => x.ShortcutDimension2Code).HasColumnName("shortcut_dimension_2_code");
        builder.Property(x => x.JobNo).HasColumnName("job_no");
        builder.Property(x => x.IndirectCost).HasColumnName("indirect_cost").HasPrecision(18, 5);
        builder.Property(x => x.QtyRcdNotInvoiced).HasColumnName("qty_rcd_not_invoiced").HasPrecision(18, 5);
        builder.Property(x => x.QuantityInvoiced).HasColumnName("quantity_invoiced").HasPrecision(18, 5);
        builder.Property(x => x.OrderNo).HasColumnName("order_no");
        builder.Property(x => x.OrderLineNo).HasColumnName("order_line_no");
        builder.Property(x => x.PayToVendorNo).HasColumnName("pay_to_vendor_no");
        builder.Property(x => x.VendorItemNo).HasColumnName("vendor_item_no");
        builder.Property(x => x.SalesOrderNo).HasColumnName("sales_order_no");
        builder.Property(x => x.SalesOrderLineNo).HasColumnName("sales_order_line_no");
        builder.Property(x => x.GenBusPostingGroup).HasColumnName("gen_bus_posting_group");
        builder.Property(x => x.GenProdPostingGroup).HasColumnName("gen_prod_posting_group");
        builder.Property(x => x.VatCalculationType).HasColumnName("vat_calculation_type");
        builder.Property(x => x.TransactionType).HasColumnName("transaction_type");
        builder.Property(x => x.TransportMethod).HasColumnName("transport_method");
        builder.Property(x => x.AttachedToLineNo).HasColumnName("attached_to_line_no");
        builder.Property(x => x.EntryPoint).HasColumnName("entry_point");
        builder.Property(x => x.Area).HasColumnName("area");
        builder.Property(x => x.TransactionSpecification).HasColumnName("transaction_specification");
        builder.Property(x => x.TaxAreaCode).HasColumnName("tax_area_code");
        builder.Property(x => x.TaxLiable).HasColumnName("tax_liable");
        builder.Property(x => x.TaxGroupCode).HasColumnName("tax_group_code");
        builder.Property(x => x.UseTax).HasColumnName("use_tax");
        builder.Property(x => x.VatBusPostingGroup).HasColumnName("vat_bus_posting_group");
        builder.Property(x => x.VatProdPostingGroup).HasColumnName("vat_prod_posting_group");
        builder.Property(x => x.BlanketOrderNo).HasColumnName("blanket_order_no");
        builder.Property(x => x.BlanketOrderLineNo).HasColumnName("blanket_order_line_no");
        builder.Property(x => x.VatBaseAmount).HasColumnName("vat_base_amount").HasPrecision(18, 5);
        builder.Property(x => x.UnitCost).HasColumnName("unit_cost").HasPrecision(18, 5);
        builder.Property(x => x.PostingDate).HasColumnName("posting_date");
        builder.Property(x => x.DimensionSetId).HasColumnName("dimension_set_id");
        builder.Property(x => x.JobTaskNo).HasColumnName("job_task_no");
        builder.Property(x => x.JobLineType).HasColumnName("job_line_type");
        builder.Property(x => x.JobUnitPrice).HasColumnName("job_unit_price").HasPrecision(18, 5);
        builder.Property(x => x.JobTotalPrice).HasColumnName("job_total_price").HasPrecision(18, 5);
        builder.Property(x => x.JobLineAmount).HasColumnName("job_line_amount").HasPrecision(18, 5);
        builder.Property(x => x.JobLineDiscountAmount).HasColumnName("job_line_discount_amount").HasPrecision(18, 5);
        builder.Property(x => x.JobLineDiscount).HasColumnName("job_line_discount").HasPrecision(18, 5);
        builder.Property(x => x.JobUnitPriceLcy).HasColumnName("job_unit_price_lcy").HasPrecision(18, 5);
        builder.Property(x => x.JobTotalPriceLcy).HasColumnName("job_total_price_lcy").HasPrecision(18, 5);
        builder.Property(x => x.JobLineAmountLcy).HasColumnName("job_line_amount_lcy").HasPrecision(18, 5);
        builder.Property(x => x.JobLineDiscAmountLcy).HasColumnName("job_line_disc_amount_lcy").HasPrecision(18, 5);
        builder.Property(x => x.JobCurrencyFactor).HasColumnName("job_currency_factor").HasPrecision(18, 5);
        builder.Property(x => x.JobCurrencyCode).HasColumnName("job_currency_code");
        builder.Property(x => x.ProdOrderNo).HasColumnName("prod_order_no");
        builder.Property(x => x.VariantCode).HasColumnName("variant_code");
        builder.Property(x => x.BinCode).HasColumnName("bin_code");
        builder.Property(x => x.QtyPerUnitOfMeasure).HasColumnName("qty_per_unit_of_measure").HasPrecision(18, 5);
        builder.Property(x => x.UnitOfMeasureCode).HasColumnName("unit_of_measure_code");
        builder.Property(x => x.QuantityBase).HasColumnName("quantity_base").HasPrecision(18, 5);
        builder.Property(x => x.QtyInvoicedBase).HasColumnName("qty_invoiced_base").HasPrecision(18, 5);
        builder.Property(x => x.FaPostingDate).HasColumnName("fa_posting_date");
        builder.Property(x => x.FaPostingType).HasColumnName("fa_posting_type");
        builder.Property(x => x.DepreciationBookCode).HasColumnName("depreciation_book_code");
        builder.Property(x => x.SalvageValue).HasColumnName("salvage_value").HasPrecision(18, 5);
        builder.Property(x => x.DeprUntilFaPostingDate).HasColumnName("depr_until_fa_posting_date");
        builder.Property(x => x.DeprAcquisitionCost).HasColumnName("depr_acquisition_cost");
        builder.Property(x => x.MaintenanceCode).HasColumnName("maintenance_code");
        builder.Property(x => x.InsuranceNo).HasColumnName("insurance_no");
        builder.Property(x => x.BudgetedFaNo).HasColumnName("budgeted_fa_no");
        builder.Property(x => x.DuplicateInDepreciationBook).HasColumnName("duplicate_in_depreciation_book");
        builder.Property(x => x.UseDuplicationList).HasColumnName("use_duplication_list");
        builder.Property(x => x.ResponsibilityCenter).HasColumnName("responsibility_center");
        builder.Property(x => x.CrossReferenceNo).HasColumnName("cross_reference_no");
        builder.Property(x => x.UnitOfMeasureCrossRef).HasColumnName("unit_of_measure_cross_ref");
        builder.Property(x => x.CrossReferenceType).HasColumnName("cross_reference_type");
        builder.Property(x => x.CrossReferenceTypeNo).HasColumnName("cross_reference_type_no");
        builder.Property(x => x.ItemCategoryCode).HasColumnName("item_category_code");
        builder.Property(x => x.Nonstock).HasColumnName("nonstock");
        builder.Property(x => x.PurchasingCode).HasColumnName("purchasing_code");
        builder.Property(x => x.ProductGroupCode).HasColumnName("product_group_code");
        builder.Property(x => x.SpecialOrderSalesNo).HasColumnName("special_order_sales_no");
        builder.Property(x => x.SpecialOrderSalesLineNo).HasColumnName("special_order_sales_line_no");
        builder.Property(x => x.RequestedReceiptDate).HasColumnName("requested_receipt_date");
        builder.Property(x => x.PromisedReceiptDate).HasColumnName("promised_receipt_date");
        builder.Property(x => x.LeadTimeCalculation).HasColumnName("lead_time_calculation");
        builder.Property(x => x.InboundWhseHandlingTime).HasColumnName("inbound_whse_handling_time");
        builder.Property(x => x.PlannedReceiptDate).HasColumnName("planned_receipt_date");
        builder.Property(x => x.OrderDate).HasColumnName("order_date");
        builder.Property(x => x.ItemChargeBaseAmount).HasColumnName("item_charge_base_amount").HasPrecision(18, 5);
        builder.Property(x => x.Correction).HasColumnName("correction");
        builder.Property(x => x.ReturnReasonCode).HasColumnName("return_reason_code");
        builder.Property(x => x.RoutingNo).HasColumnName("routing_no");
        builder.Property(x => x.OperationNo).HasColumnName("operation_no");
        builder.Property(x => x.WorkCenterNo).HasColumnName("work_center_no");
        builder.Property(x => x.ProdOrderLineNo).HasColumnName("prod_order_line_no");
        builder.Property(x => x.OverheadRate).HasColumnName("overhead_rate").HasPrecision(18, 5);
        builder.Property(x => x.RoutingReferenceNo).HasColumnName("routing_reference_no");
    }
}
