using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Metadata.Builders;
using NexusBilling.Core.Domain.Common;
using NexusBilling.Core.Domain.Purchasing.Entities;

namespace NexusBilling.Infrastructure.Persistence.Purchasing.Configurations;

public class PurchaseHeaderArchiveConfiguration : IEntityTypeConfiguration<PurchaseHeaderArchive>
{
    public void Configure(EntityTypeBuilder<PurchaseHeaderArchive> builder)
    {
        builder.ToTable("purchase_header_archive", "purchasing");
        builder.HasKey(x => x.Id);
        builder.Property(x => x.TenantId).HasConversion(v => v.Value, v => TenantIdentifier.Create(v)).HasColumnName("tenant_id").IsRequired();
        builder.Property(x => x.DocumentType).HasColumnName("document_type");
        builder.Property(x => x.BuyFromVendorNo).HasColumnName("buy_from_vendor_no");
        builder.Property(x => x.No).HasColumnName("no");
        builder.Property(x => x.PayToVendorNo).HasColumnName("pay_to_vendor_no");
        builder.Property(x => x.PayToName).HasColumnName("pay_to_name");
        builder.Property(x => x.PayToName2).HasColumnName("pay_to_name_2");
        builder.Property(x => x.PayToAddress).HasColumnName("pay_to_address");
        builder.Property(x => x.PayToAddress2).HasColumnName("pay_to_address_2");
        builder.Property(x => x.PayToCity).HasColumnName("pay_to_city");
        builder.Property(x => x.PayToContact).HasColumnName("pay_to_contact");
        builder.Property(x => x.YourReference).HasColumnName("your_reference");
        builder.Property(x => x.ShipToCode).HasColumnName("ship_to_code");
        builder.Property(x => x.ShipToName).HasColumnName("ship_to_name");
        builder.Property(x => x.ShipToName2).HasColumnName("ship_to_name_2");
        builder.Property(x => x.ShipToAddress).HasColumnName("ship_to_address");
        builder.Property(x => x.ShipToAddress2).HasColumnName("ship_to_address_2");
        builder.Property(x => x.ShipToCity).HasColumnName("ship_to_city");
        builder.Property(x => x.ShipToContact).HasColumnName("ship_to_contact");
        builder.Property(x => x.OrderDate).HasColumnName("order_date");
        builder.Property(x => x.PostingDate).HasColumnName("posting_date");
        builder.Property(x => x.ExpectedReceiptDate).HasColumnName("expected_receipt_date");
        builder.Property(x => x.PostingDescription).HasColumnName("posting_description");
        builder.Property(x => x.PaymentTermsCode).HasColumnName("payment_terms_code");
        builder.Property(x => x.DueDate).HasColumnName("due_date");
        builder.Property(x => x.PaymentDiscount).HasColumnName("payment_discount").HasPrecision(18, 5);
        builder.Property(x => x.PmtDiscountDate).HasColumnName("pmt_discount_date");
        builder.Property(x => x.ShipmentMethodCode).HasColumnName("shipment_method_code");
        builder.Property(x => x.LocationCode).HasColumnName("location_code");
        builder.Property(x => x.ShortcutDimension1Code).HasColumnName("shortcut_dimension_1_code");
        builder.Property(x => x.ShortcutDimension2Code).HasColumnName("shortcut_dimension_2_code");
        builder.Property(x => x.VendorPostingGroup).HasColumnName("vendor_posting_group");
        builder.Property(x => x.CurrencyCode).HasColumnName("currency_code");
        builder.Property(x => x.CurrencyFactor).HasColumnName("currency_factor").HasPrecision(18, 5);
        builder.Property(x => x.PricesIncludingVat).HasColumnName("prices_including_vat");
        builder.Property(x => x.InvoiceDiscCode).HasColumnName("invoice_disc_code");
        builder.Property(x => x.LanguageCode).HasColumnName("language_code");
        builder.Property(x => x.PurchaserCode).HasColumnName("purchaser_code");
        builder.Property(x => x.OrderClass).HasColumnName("order_class");
        builder.Property(x => x.NoPrinted).HasColumnName("no_printed");
        builder.Property(x => x.OnHold).HasColumnName("on_hold");
        builder.Property(x => x.AppliesToDocType).HasColumnName("applies_to_doc_type");
        builder.Property(x => x.AppliesToDocNo).HasColumnName("applies_to_doc_no");
        builder.Property(x => x.BalAccountNo).HasColumnName("bal_account_no");
        builder.Property(x => x.Receive).HasColumnName("receive");
        builder.Property(x => x.Invoice).HasColumnName("invoice");
        builder.Property(x => x.ReceivingNo).HasColumnName("receiving_no");
        builder.Property(x => x.PostingNo).HasColumnName("posting_no");
        builder.Property(x => x.LastReceivingNo).HasColumnName("last_receiving_no");
        builder.Property(x => x.LastPostingNo).HasColumnName("last_posting_no");
        builder.Property(x => x.VendorOrderNo).HasColumnName("vendor_order_no");
        builder.Property(x => x.VendorShipmentNo).HasColumnName("vendor_shipment_no");
        builder.Property(x => x.VendorInvoiceNo).HasColumnName("vendor_invoice_no");
        builder.Property(x => x.VendorCrMemoNo).HasColumnName("vendor_cr_memo_no");
        builder.Property(x => x.VatRegistrationNo).HasColumnName("vat_registration_no");
        builder.Property(x => x.SellToCustomerNo).HasColumnName("sell_to_customer_no");
        builder.Property(x => x.ReasonCode).HasColumnName("reason_code");
        builder.Property(x => x.GenBusPostingGroup).HasColumnName("gen_bus_posting_group");
        builder.Property(x => x.TransactionType).HasColumnName("transaction_type");
        builder.Property(x => x.TransportMethod).HasColumnName("transport_method");
        builder.Property(x => x.VatCountryRegionCode).HasColumnName("vat_country_region_code");
        builder.Property(x => x.BuyFromVendorName).HasColumnName("buy_from_vendor_name");
        builder.Property(x => x.BuyFromVendorName2).HasColumnName("buy_from_vendor_name_2");
        builder.Property(x => x.BuyFromAddress).HasColumnName("buy_from_address");
        builder.Property(x => x.BuyFromAddress2).HasColumnName("buy_from_address_2");
        builder.Property(x => x.BuyFromCity).HasColumnName("buy_from_city");
        builder.Property(x => x.BuyFromContact).HasColumnName("buy_from_contact");
        builder.Property(x => x.PayToPostCode).HasColumnName("pay_to_post_code");
        builder.Property(x => x.PayToCounty).HasColumnName("pay_to_county");
        builder.Property(x => x.PayToCountryRegionCode).HasColumnName("pay_to_country_region_code");
        builder.Property(x => x.BuyFromPostCode).HasColumnName("buy_from_post_code");
        builder.Property(x => x.BuyFromCounty).HasColumnName("buy_from_county");
        builder.Property(x => x.BuyFromCountryRegionCode).HasColumnName("buy_from_country_region_code");
        builder.Property(x => x.ShipToPostCode).HasColumnName("ship_to_post_code");
        builder.Property(x => x.ShipToCounty).HasColumnName("ship_to_county");
        builder.Property(x => x.ShipToCountryRegionCode).HasColumnName("ship_to_country_region_code");
        builder.Property(x => x.BalAccountType).HasColumnName("bal_account_type");
        builder.Property(x => x.OrderAddressCode).HasColumnName("order_address_code");
        builder.Property(x => x.EntryPoint).HasColumnName("entry_point");
        builder.Property(x => x.Correction).HasColumnName("correction");
        builder.Property(x => x.DocumentDate).HasColumnName("document_date");
        builder.Property(x => x.Area).HasColumnName("area");
        builder.Property(x => x.TransactionSpecification).HasColumnName("transaction_specification");
        builder.Property(x => x.PaymentMethodCode).HasColumnName("payment_method_code");
        builder.Property(x => x.NoSeries).HasColumnName("no_series");
        builder.Property(x => x.PostingNoSeries).HasColumnName("posting_no_series");
        builder.Property(x => x.ReceivingNoSeries).HasColumnName("receiving_no_series");
        builder.Property(x => x.TaxAreaCode).HasColumnName("tax_area_code");
        builder.Property(x => x.TaxLiable).HasColumnName("tax_liable");
        builder.Property(x => x.VatBusPostingGroup).HasColumnName("vat_bus_posting_group");
        builder.Property(x => x.AppliesToId).HasColumnName("applies_to_id");
        builder.Property(x => x.VatBaseDiscount).HasColumnName("vat_base_discount").HasPrecision(18, 5);
        builder.Property(x => x.Status).HasColumnName("status");
        builder.Property(x => x.InvoiceDiscountCalculation).HasColumnName("invoice_discount_calculation");
        builder.Property(x => x.InvoiceDiscountValue).HasColumnName("invoice_discount_value").HasPrecision(18, 5);
        builder.Property(x => x.SendIcDocument).HasColumnName("send_ic_document");
        builder.Property(x => x.IcStatus).HasColumnName("ic_status");
        builder.Property(x => x.BuyFromIcPartnerCode).HasColumnName("buy_from_ic_partner_code");
        builder.Property(x => x.PayToIcPartnerCode).HasColumnName("pay_to_ic_partner_code");
        builder.Property(x => x.IcDirection).HasColumnName("ic_direction");
        builder.Property(x => x.PrepaymentNo).HasColumnName("prepayment_no");
        builder.Property(x => x.LastPrepaymentNo).HasColumnName("last_prepayment_no");
        builder.Property(x => x.PrepmtCrMemoNo).HasColumnName("prepmt_cr_memo_no");
        builder.Property(x => x.LastPrepmtCrMemoNo).HasColumnName("last_prepmt_cr_memo_no");
        builder.Property(x => x.Prepayment).HasColumnName("prepayment").HasPrecision(18, 5);
        builder.Property(x => x.PrepaymentNoSeries).HasColumnName("prepayment_no_series");
        builder.Property(x => x.CompressPrepayment).HasColumnName("compress_prepayment");
        builder.Property(x => x.PrepaymentDueDate).HasColumnName("prepayment_due_date");
        builder.Property(x => x.PrepmtCrMemoNoSeries).HasColumnName("prepmt_cr_memo_no_series");
        builder.Property(x => x.PrepmtPostingDescription).HasColumnName("prepmt_posting_description");
        builder.Property(x => x.PrepmtPmtDiscountDate).HasColumnName("prepmt_pmt_discount_date");
        builder.Property(x => x.PrepmtPaymentTermsCode).HasColumnName("prepmt_payment_terms_code");
        builder.Property(x => x.PrepmtPaymentDiscount).HasColumnName("prepmt_payment_discount").HasPrecision(18, 5);
        builder.Property(x => x.PurchaseQuoteNo).HasColumnName("purchase_quote_no");
        builder.Property(x => x.DimensionSetId).HasColumnName("dimension_set_id");
        builder.Property(x => x.InteractionExist).HasColumnName("interaction_exist");
        builder.Property(x => x.TimeArchived).HasColumnName("time_archived");
        builder.Property(x => x.DateArchived).HasColumnName("date_archived");
        builder.Property(x => x.ArchivedBy).HasColumnName("archived_by");
        builder.Property(x => x.VersionNo).HasColumnName("version_no");
        builder.Property(x => x.DocNoOccurrence).HasColumnName("doc_no_occurrence");
        builder.Property(x => x.CampaignNo).HasColumnName("campaign_no");
        builder.Property(x => x.BuyFromContactNo).HasColumnName("buy_from_contact_no");
        builder.Property(x => x.PayToContactNo).HasColumnName("pay_to_contact_no");
        builder.Property(x => x.ResponsibilityCenter).HasColumnName("responsibility_center");
        builder.Property(x => x.PostingFromWhseRef).HasColumnName("posting_from_whse_ref");
        builder.Property(x => x.RequestedReceiptDate).HasColumnName("requested_receipt_date");
        builder.Property(x => x.PromisedReceiptDate).HasColumnName("promised_receipt_date");
        builder.Property(x => x.LeadTimeCalculation).HasColumnName("lead_time_calculation");
        builder.Property(x => x.InboundWhseHandlingTime).HasColumnName("inbound_whse_handling_time");
        builder.Property(x => x.VendorAuthorizationNo).HasColumnName("vendor_authorization_no");
        builder.Property(x => x.ReturnShipmentNo).HasColumnName("return_shipment_no");
        builder.Property(x => x.ReturnShipmentNoSeries).HasColumnName("return_shipment_no_series");
        builder.Property(x => x.Ship).HasColumnName("ship");
        builder.Property(x => x.LastReturnShipmentNo).HasColumnName("last_return_shipment_no");
        builder.Property(x => x.AssignedUserId).HasColumnName("assigned_user_id");
    }
}
