using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Metadata.Builders;
using NexusBilling.Core.Domain.Common;
using NexusBilling.Core.Domain.Purchasing.Entities;

namespace NexusBilling.Infrastructure.Persistence.Purchasing.Configurations;

public class RequisitionLineConfiguration : IEntityTypeConfiguration<RequisitionLine>
{
    public void Configure(EntityTypeBuilder<RequisitionLine> builder)
    {
        builder.ToTable("requisition_line", "purchasing");
        builder.HasKey(x => x.Id);
        builder.Property(x => x.TenantId).HasConversion(v => v.Value, v => TenantIdentifier.Create(v)).HasColumnName("tenant_id").IsRequired();
        builder.Property(x => x.WorksheetTemplateName).HasColumnName("worksheet_template_name");
        builder.Property(x => x.JournalBatchName).HasColumnName("journal_batch_name");
        builder.Property(x => x.LineNo).HasColumnName("line_no");
        builder.Property(x => x.Type).HasColumnName("type");
        builder.Property(x => x.No).HasColumnName("no");
        builder.Property(x => x.Description).HasColumnName("description");
        builder.Property(x => x.Description2).HasColumnName("description_2");
        builder.Property(x => x.Quantity).HasColumnName("quantity").HasPrecision(18, 5);
        builder.Property(x => x.VendorNo).HasColumnName("vendor_no");
        builder.Property(x => x.DirectUnitCost).HasColumnName("direct_unit_cost").HasPrecision(18, 5);
        builder.Property(x => x.DueDate).HasColumnName("due_date");
        builder.Property(x => x.RequesterId).HasColumnName("requester_id");
        builder.Property(x => x.Confirmed).HasColumnName("confirmed");
        builder.Property(x => x.ShortcutDimension1Code).HasColumnName("shortcut_dimension_1_code");
        builder.Property(x => x.ShortcutDimension2Code).HasColumnName("shortcut_dimension_2_code");
        builder.Property(x => x.LocationCode).HasColumnName("location_code");
        builder.Property(x => x.RecurringMethod).HasColumnName("recurring_method");
        builder.Property(x => x.ExpirationDate).HasColumnName("expiration_date");
        builder.Property(x => x.RecurringFrequency).HasColumnName("recurring_frequency");
        builder.Property(x => x.OrderDate).HasColumnName("order_date");
        builder.Property(x => x.VendorItemNo).HasColumnName("vendor_item_no");
        builder.Property(x => x.SalesOrderNo).HasColumnName("sales_order_no");
        builder.Property(x => x.SalesOrderLineNo).HasColumnName("sales_order_line_no");
        builder.Property(x => x.SellToCustomerNo).HasColumnName("sell_to_customer_no");
        builder.Property(x => x.ShipToCode).HasColumnName("ship_to_code");
        builder.Property(x => x.OrderAddressCode).HasColumnName("order_address_code");
        builder.Property(x => x.CurrencyCode).HasColumnName("currency_code");
        builder.Property(x => x.CurrencyFactor).HasColumnName("currency_factor").HasPrecision(18, 5);
        builder.Property(x => x.DimensionSetId).HasColumnName("dimension_set_id");
        builder.Property(x => x.ProdOrderNo).HasColumnName("prod_order_no");
        builder.Property(x => x.VariantCode).HasColumnName("variant_code");
        builder.Property(x => x.BinCode).HasColumnName("bin_code");
        builder.Property(x => x.QtyPerUnitOfMeasure).HasColumnName("qty_per_unit_of_measure").HasPrecision(18, 5);
        builder.Property(x => x.UnitOfMeasureCode).HasColumnName("unit_of_measure_code");
        builder.Property(x => x.QuantityBase).HasColumnName("quantity_base").HasPrecision(18, 5);
        builder.Property(x => x.DemandType).HasColumnName("demand_type");
        builder.Property(x => x.DemandSubtype).HasColumnName("demand_subtype");
        builder.Property(x => x.DemandOrderNo).HasColumnName("demand_order_no");
        builder.Property(x => x.DemandLineNo).HasColumnName("demand_line_no");
        builder.Property(x => x.DemandRefNo).HasColumnName("demand_ref_no");
        builder.Property(x => x.Status).HasColumnName("status");
        builder.Property(x => x.DemandDate).HasColumnName("demand_date");
        builder.Property(x => x.DemandQuantity).HasColumnName("demand_quantity").HasPrecision(18, 5);
        builder.Property(x => x.DemandQuantityBase).HasColumnName("demand_quantity_base").HasPrecision(18, 5);
        builder.Property(x => x.NeededQuantity).HasColumnName("needed_quantity").HasPrecision(18, 5);
        builder.Property(x => x.NeededQuantityBase).HasColumnName("needed_quantity_base").HasPrecision(18, 5);
        builder.Property(x => x.Reserve).HasColumnName("reserve");
        builder.Property(x => x.QtyPerUomDemand).HasColumnName("qty_per_uom_demand").HasPrecision(18, 5);
        builder.Property(x => x.UnitOfMeasureCodeDemand).HasColumnName("unit_of_measure_code_demand");
        builder.Property(x => x.SupplyFrom).HasColumnName("supply_from");
        builder.Property(x => x.OriginalItemNo).HasColumnName("original_item_no");
        builder.Property(x => x.OriginalVariantCode).HasColumnName("original_variant_code");
        builder.Property(x => x.Level).HasColumnName("level");
        builder.Property(x => x.DemandQtyAvailable).HasColumnName("demand_qty_available").HasPrecision(18, 5);
        builder.Property(x => x.UserId).HasColumnName("user_id");
        builder.Property(x => x.ItemCategoryCode).HasColumnName("item_category_code");
        builder.Property(x => x.Nonstock).HasColumnName("nonstock");
        builder.Property(x => x.PurchasingCode).HasColumnName("purchasing_code");
        builder.Property(x => x.ProductGroupCode).HasColumnName("product_group_code");
        builder.Property(x => x.TransferFromCode).HasColumnName("transfer_from_code");
        builder.Property(x => x.TransferShipmentDate).HasColumnName("transfer_shipment_date");
        builder.Property(x => x.LineDiscount).HasColumnName("line_discount").HasPrecision(18, 5);
        builder.Property(x => x.RoutingNo).HasColumnName("routing_no");
        builder.Property(x => x.OperationNo).HasColumnName("operation_no");
        builder.Property(x => x.WorkCenterNo).HasColumnName("work_center_no");
        builder.Property(x => x.ProdOrderLineNo).HasColumnName("prod_order_line_no");
        builder.Property(x => x.MpsOrder).HasColumnName("mps_order");
        builder.Property(x => x.PlanningFlexibility).HasColumnName("planning_flexibility");
        builder.Property(x => x.RoutingReferenceNo).HasColumnName("routing_reference_no");
        builder.Property(x => x.GenProdPostingGroup).HasColumnName("gen_prod_posting_group");
        builder.Property(x => x.GenBusinessPostingGroup).HasColumnName("gen_business_posting_group");
        builder.Property(x => x.LowLevelCode).HasColumnName("low_level_code");
        builder.Property(x => x.ProductionBomVersionCode).HasColumnName("production_bom_version_code");
        builder.Property(x => x.RoutingVersionCode).HasColumnName("routing_version_code");
        builder.Property(x => x.RoutingType).HasColumnName("routing_type");
        builder.Property(x => x.OriginalQuantity).HasColumnName("original_quantity").HasPrecision(18, 5);
        builder.Property(x => x.FinishedQuantity).HasColumnName("finished_quantity").HasPrecision(18, 5);
        builder.Property(x => x.RemainingQuantity).HasColumnName("remaining_quantity").HasPrecision(18, 5);
        builder.Property(x => x.OriginalDueDate).HasColumnName("original_due_date");
        builder.Property(x => x.Scrap).HasColumnName("scrap").HasPrecision(18, 5);
        builder.Property(x => x.StartingDate).HasColumnName("starting_date");
        builder.Property(x => x.StartingTime).HasColumnName("starting_time");
        builder.Property(x => x.EndingDate).HasColumnName("ending_date");
        builder.Property(x => x.EndingTime).HasColumnName("ending_time");
        builder.Property(x => x.ProductionBomNo).HasColumnName("production_bom_no");
        builder.Property(x => x.IndirectCost).HasColumnName("indirect_cost").HasPrecision(18, 5);
        builder.Property(x => x.OverheadRate).HasColumnName("overhead_rate").HasPrecision(18, 5);
        builder.Property(x => x.UnitCost).HasColumnName("unit_cost").HasPrecision(18, 5);
        builder.Property(x => x.CostAmount).HasColumnName("cost_amount").HasPrecision(18, 5);
        builder.Property(x => x.ReplenishmentSystem).HasColumnName("replenishment_system");
        builder.Property(x => x.RefOrderNo).HasColumnName("ref_order_no");
        builder.Property(x => x.RefOrderType).HasColumnName("ref_order_type");
        builder.Property(x => x.RefOrderStatus).HasColumnName("ref_order_status");
        builder.Property(x => x.RefLineNo).HasColumnName("ref_line_no");
        builder.Property(x => x.NoSeries).HasColumnName("no_series");
        builder.Property(x => x.FinishedQtyBase).HasColumnName("finished_qty_base").HasPrecision(18, 5);
        builder.Property(x => x.RemainingQtyBase).HasColumnName("remaining_qty_base").HasPrecision(18, 5);
        builder.Property(x => x.RelatedToPlanningLine).HasColumnName("related_to_planning_line");
        builder.Property(x => x.PlanningLevel).HasColumnName("planning_level");
        builder.Property(x => x.PlanningLineOrigin).HasColumnName("planning_line_origin");
        builder.Property(x => x.ActionMessage).HasColumnName("action_message");
        builder.Property(x => x.AcceptActionMessage).HasColumnName("accept_action_message");
        builder.Property(x => x.NetQuantityBase).HasColumnName("net_quantity_base").HasPrecision(18, 5);
        builder.Property(x => x.StartingDateTime).HasColumnName("starting_date_time");
        builder.Property(x => x.EndingDateTime).HasColumnName("ending_date_time");
        builder.Property(x => x.OrderPromisingId).HasColumnName("order_promising_id");
        builder.Property(x => x.OrderPromisingLineNo).HasColumnName("order_promising_line_no");
        builder.Property(x => x.OrderPromisingLineId).HasColumnName("order_promising_line_id");
    }
}
