using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Metadata.Builders;
using NexusBilling.Core.Domain.Common;
using NexusBilling.Core.Domain.Purchasing.Entities;

namespace NexusBilling.Infrastructure.Persistence.Purchasing.Configurations;

public class ReturnShipmentHeaderConfiguration : IEntityTypeConfiguration<ReturnShipmentHeader>
{
    public void Configure(EntityTypeBuilder<ReturnShipmentHeader> builder)
    {
        builder.ToTable("return_shipment_header", "purchasing");
        builder.HasKey(x => x.Id);
        builder.Property(x => x.TenantId).HasConversion(v => v.Value, v => TenantIdentifier.Create(v)).HasColumnName("tenant_id").IsRequired();
        builder.Property(x => x.BuyFromVendorNo).HasColumnName("buy_from_vendor_no");
        builder.Property(x => x.No).HasColumnName("no");
        builder.Property(x => x.PayToVendorNo).HasColumnName("pay_to_vendor_no");
        builder.Property(x => x.PayToName).HasColumnName("pay_to_name");
        builder.Property(x => x.PayToName2).HasColumnName("pay_to_name_2");
        builder.Property(x => x.PayToAddress).HasColumnName("pay_to_address");
        builder.Property(x => x.PayToAddress2).HasColumnName("pay_to_address_2");
        builder.Property(x => x.PayToCity).HasColumnName("pay_to_city");
        builder.Property(x => x.PayToContact).HasColumnName("pay_to_contact");
        builder.Property(x => x.YourReference).HasColumnName("your_reference");
        builder.Property(x => x.ShipToCode).HasColumnName("ship_to_code");
        builder.Property(x => x.ShipToName).HasColumnName("ship_to_name");
        builder.Property(x => x.ShipToName2).HasColumnName("ship_to_name_2");
        builder.Property(x => x.ShipToAddress).HasColumnName("ship_to_address");
        builder.Property(x => x.ShipToAddress2).HasColumnName("ship_to_address_2");
        builder.Property(x => x.ShipToCity).HasColumnName("ship_to_city");
        builder.Property(x => x.ShipToContact).HasColumnName("ship_to_contact");
        builder.Property(x => x.PostingDate).HasColumnName("posting_date");
        builder.Property(x => x.ExpectedReceiptDate).HasColumnName("expected_receipt_date");
        builder.Property(x => x.PostingDescription).HasColumnName("posting_description");
        builder.Property(x => x.PaymentTermsCode).HasColumnName("payment_terms_code");
        builder.Property(x => x.DueDate).HasColumnName("due_date");
        builder.Property(x => x.PaymentDiscount).HasColumnName("payment_discount").HasPrecision(18, 5);
        builder.Property(x => x.PmtDiscountDate).HasColumnName("pmt_discount_date");
        builder.Property(x => x.ShipmentMethodCode).HasColumnName("shipment_method_code");
        builder.Property(x => x.LocationCode).HasColumnName("location_code");
        builder.Property(x => x.ShortcutDimension1Code).HasColumnName("shortcut_dimension_1_code");
        builder.Property(x => x.ShortcutDimension2Code).HasColumnName("shortcut_dimension_2_code");
        builder.Property(x => x.VendorPostingGroup).HasColumnName("vendor_posting_group");
        builder.Property(x => x.CurrencyCode).HasColumnName("currency_code");
        builder.Property(x => x.CurrencyFactor).HasColumnName("currency_factor").HasPrecision(18, 5);
        builder.Property(x => x.InvoiceDiscCode).HasColumnName("invoice_disc_code");
        builder.Property(x => x.LanguageCode).HasColumnName("language_code");
        builder.Property(x => x.PurchaserCode).HasColumnName("purchaser_code");
        builder.Property(x => x.NoPrinted).HasColumnName("no_printed");
        builder.Property(x => x.OnHold).HasColumnName("on_hold");
        builder.Property(x => x.AppliesToDocType).HasColumnName("applies_to_doc_type");
        builder.Property(x => x.AppliesToDocNo).HasColumnName("applies_to_doc_no");
        builder.Property(x => x.BalAccountNo).HasColumnName("bal_account_no");
        builder.Property(x => x.VatRegistrationNo).HasColumnName("vat_registration_no");
        builder.Property(x => x.SellToCustomerNo).HasColumnName("sell_to_customer_no");
        builder.Property(x => x.ReasonCode).HasColumnName("reason_code");
        builder.Property(x => x.GenBusPostingGroup).HasColumnName("gen_bus_posting_group");
        builder.Property(x => x.TransactionType).HasColumnName("transaction_type");
        builder.Property(x => x.TransportMethod).HasColumnName("transport_method");
        builder.Property(x => x.VatCountryRegionCode).HasColumnName("vat_country_region_code");
        builder.Property(x => x.BuyFromVendorName).HasColumnName("buy_from_vendor_name");
        builder.Property(x => x.BuyFromVendorName2).HasColumnName("buy_from_vendor_name_2");
        builder.Property(x => x.BuyFromAddress).HasColumnName("buy_from_address");
        builder.Property(x => x.BuyFromAddress2).HasColumnName("buy_from_address_2");
        builder.Property(x => x.BuyFromCity).HasColumnName("buy_from_city");
        builder.Property(x => x.BuyFromContact).HasColumnName("buy_from_contact");
        builder.Property(x => x.PayToPostCode).HasColumnName("pay_to_post_code");
        builder.Property(x => x.PayToCounty).HasColumnName("pay_to_county");
        builder.Property(x => x.PayToCountryRegionCode).HasColumnName("pay_to_country_region_code");
        builder.Property(x => x.BuyFromPostCode).HasColumnName("buy_from_post_code");
        builder.Property(x => x.BuyFromCounty).HasColumnName("buy_from_county");
        builder.Property(x => x.BuyFromCountryRegionCode).HasColumnName("buy_from_country_region_code");
        builder.Property(x => x.ShipToPostCode).HasColumnName("ship_to_post_code");
        builder.Property(x => x.ShipToCounty).HasColumnName("ship_to_county");
        builder.Property(x => x.ShipToCountryRegionCode).HasColumnName("ship_to_country_region_code");
        builder.Property(x => x.BalAccountType).HasColumnName("bal_account_type");
        builder.Property(x => x.OrderAddressCode).HasColumnName("order_address_code");
        builder.Property(x => x.EntryPoint).HasColumnName("entry_point");
        builder.Property(x => x.Correction).HasColumnName("correction");
        builder.Property(x => x.DocumentDate).HasColumnName("document_date");
        builder.Property(x => x.Area).HasColumnName("area");
        builder.Property(x => x.TransactionSpecification).HasColumnName("transaction_specification");
        builder.Property(x => x.PaymentMethodCode).HasColumnName("payment_method_code");
        builder.Property(x => x.NoSeries).HasColumnName("no_series");
        builder.Property(x => x.UserId).HasColumnName("user_id");
        builder.Property(x => x.SourceCode).HasColumnName("source_code");
        builder.Property(x => x.TaxAreaCode).HasColumnName("tax_area_code");
        builder.Property(x => x.TaxLiable).HasColumnName("tax_liable");
        builder.Property(x => x.VatBusPostingGroup).HasColumnName("vat_bus_posting_group");
        builder.Property(x => x.VatBaseDiscount).HasColumnName("vat_base_discount").HasPrecision(18, 5);
        builder.Property(x => x.DimensionSetId).HasColumnName("dimension_set_id");
        builder.Property(x => x.CampaignNo).HasColumnName("campaign_no");
        builder.Property(x => x.BuyFromContactNo).HasColumnName("buy_from_contact_no");
        builder.Property(x => x.PayToContactNo).HasColumnName("pay_to_contact_no");
        builder.Property(x => x.ResponsibilityCenter).HasColumnName("responsibility_center");
        builder.Property(x => x.VendorAuthorizationNo).HasColumnName("vendor_authorization_no");
        builder.Property(x => x.ReturnOrderNo).HasColumnName("return_order_no");
        builder.Property(x => x.ReturnOrderNoSeries).HasColumnName("return_order_no_series");
    }
}
